### ISSUE TITLE
Fix for not getting search results on Mac- how to implement into plugins/qBittorrent?

### ISSUE THREAD

**Issue by tvqt** [qbittorrent/search-plugins#187] opened 2021-12-19 06:45 UTC
Hi everyone, 

I was having some issues with search within qbittorrent, and I managed to find a fix- I included it below- how can this be pushed to people using Mac?

*Background*
 I was getting results with some plugins, such as limetorrents, but not others, such as bt4g. Bt4g worked from the command line, and after downloading source files, I narrowed the problem down to the SSL certificates used by Python.

*Solution*
Run the "Install Certificates.command" file within the Python folder in Applications (in my case, it was called Python 3.9, if you are using a different version, it might be a different number). Alternatively, run this in Terminal:

`/Applications/Python\ 3.9/Install\ Certificates.command`

*Question*
How can this be pushed out, so people no longer encounter this issue? I guess it would be preferable if there were something in qbittorrent, but maybe updating all the plugins is the only option. What do you think?

**Comment by p060477** [comment] 2021-12-19 13:32
hi!....i really do not have this folder in my python..vers 3.6.6150
i've win 10 home 64 and i run qbit 4.3.4 having no issues in search results

**Comment by Maurafarah7** [comment] 2021-12-19 18:11
Hi! 

Thanks a lot! 

This command

/Applications/Python\ 3.10/Install\ Certificates.command

(I´ve had to change 3.9 for 3.10) fixed the issue! Now I get lots of results!

Thanks a lot!! :-)

Best regards,

Mauri

**Comment by p060477** [comment] 2021-12-19 18:17
could you pls tell us.
which s.o have you..?? windows..linux or...?
and where do you start that command ...?
"/Applications/Python\ 3.10/Install\ Certificates.command"
thxs in adv
cheers

**Comment by Maurafarah7** [comment] 2021-12-19 18:22
Hi, Im running Mac OS Monterey
I opened the terminal and ran /Applications/Python\ 3.10/Install\ Certificates.command

Good luck mate! :-)

**Comment by p060477** [comment] 2021-12-19 18:25
thxs so much mate!!
now it is finally clear that this should not fix in windows!! thxs for let me saving precious time!

**Comment by p060477** [comment] 2021-12-19 18:33
python -m pip install certifi
this is the command line in dos for win 10
for all who care or need!

**Comment by lorian9744** [comment] 2022-02-02 09:51
Hi, i'm using win 10 with python 3.10. When I type the command in cmd, it tells me that python can't be found, can u help me?

**Comment by tvqt** [comment] 2022-02-08 08:06
hi @lorian9744 
this sounds like a different issue to the one this one is addressing- it's both on a different operating system, and it's a different issue entirely feel free to open a new issue 

If you are having trouble with Python installation/cmd seeing your Python install, then there's plenty of help on places like StackOverflow- [here is one example](https://stackoverflow.com/questions/67933236/python-not-found-on-windows) - have a google around and see what happens 🙂

If you're sure there's an issue with qbittorrent, consider opening an issue of your own!

I'd really appreciate it if discussions of Windows problems and Python installation problems could be not in this thread, so the initial issue which prompted the thread can be focussed on (and hopefully solved!). Thanks! :)

**Comment by godzfire** [comment] 2022-07-30 22:12
Note this does fix the Search Plugins issue I posted here: 

[MacOS Monterey 12.x] Search plugins completely broken / do not return any search results
https://github.com/qbittorrent/qBittorrent/issues/16889

It would still be nice for this to be fixed in the next version. Will this break with every new QBT update?

**Comment by vitaly-cm** [comment] 2022-08-22 07:47
I had the same issue with 4.4.3.1. I did the thing with certificates and it didn't solve the issue. I installed 4.4.2 and the problem is gone.

**Comment by ngosang** [comment] 2022-09-24 21:24
I don't know about macOS but it's working in Windows and Linux.
Install Python 3.10, delete this folder `~/Library/Application Support/qBittorrent/nova3` and restart qBittorrent.

**Closed by ngosang** 2022-09-24 21:24 UTC

**Comment by kemalfx** [comment] 2024-10-23 09:26
It worked, thanks mate

**Comment by AK4EVA1** [comment] 2025-09-25 02:54
Thanks this worked for me!!!
